### ISSUE TITLE
Write test cases

### ISSUE THREAD

**Issue by misberner** [LearnLib/automatalib#1]
Create TestNG test cases

**Comment by mtf90** [comment]
I added support for jacoco coverage analysis and set up coveralls.io integration to have a nice overview/PR support.

Let's improve these measly 37%.

**Comment by mtf90** [comment]
While writing tests is an ongoing effort, I think hitting 80% coverage is a satisfying milestone that makes *writing test cases* no longer a critical issue anymore.
