### ISSUE TITLE
Renaming COPYING.txt to LICENSE

### ISSUE THREAD

**Issue by johnament** [LearnLib/automatalib#13]
To clean up the licensing of the project, I would recommend you rename this file.

**Comment by stovocor** [comment]
How does this "clean up" the licensing? According to the [GitHub help page](https://help.github.com/articles/open-source-licensing/), it does not matter in which file the license is found.

> As long as your intention is clear, you can place your license information wherever you like.

And it seems that GitHub detected the license anyway.

**Comment by mtf90** [comment]
While github seems to be able to infer the licence from a COPYING.txt file just fine, the referenced help page suggest naming the license file `LICENSE.txt` or `LICENSE.md`. I think going with the convention is reasonable.
