### ISSUE TITLE
Make an automaton out of a AUT

### ISSUE THREAD

**Issue by omarzd** [LearnLib/automatalib#14]
Hello. Can I create an automaton from the AUT format explained [here](http://cadp.inria.fr/man/aut.html)?
Thank you

**Comment by mtf90** [comment]
Dear @omarzd, currently this is not possible -- the automatalib-serialization module only covers the SAF and TAF format.

Although looking at the AUT format it is very simple which is nice. I might look into writing a small serializer in the future to get myself in touch with JavaCC.

**Comment by mtf90** [comment]
Dear @omarzd, as you can see I added Serializers for the AUT format. Unfortunately this was not possible with JavaCC to due the nature of the grammar (or maybe with a lot of hacking) but for you as an end user, this should not matter ;).

Right now, the serializers are not embedded into the existing "SerializationProvider" landscape. I'm planning to refactor these interfaces and I integrate the AUTWriter/Reader afterwards.

**Comment by omarzd** [comment]
Thank you. I appreciate this. I'll give feedback once I try it out.
