### ISSUE TITLE
Javadoc missing

### ISSUE THREAD

**Issue by omarzd** [LearnLib/automatalib#15]
Hello. [This wiki page](https://github.com/misberner/automatalib/wiki/API-Documentation) says very assuredly "Here you will find the online Javadoc for AutomataLib", yet there you will **not** find the online Javadoc for AutomataLib!

**Comment by mtf90** [comment]
I think the best solution might be, to just delete this wiki page. The main README already links to the latest JavaDoc and I see no benefit in managing this information multiple times. 

Do you think, the README link is easy enough to find?

**Comment by omarzd** [comment]
Yes, I agree on deleting the wiki page. But perhaps in the README put the API link under a clear header saying API Documentation instead of under 'Resources'.
