### ISSUE TITLE
CompactMoore

### ISSUE THREAD

**Issue by z11panyan** [LearnLib/automatalib#44]
A compilation error occurred when we build install the automatalib. As described next: 
```
Description	Resource	Path	Location	Type
Duplicate methods named addTransition with the parameters (S, I, T) and (S, I, T) are defined by the type MutableDeterministic<Integer,I,Integer,O,Void>	CompactMoore.java	/automata-core/src/main/java/net/automatalib/automata/transducers/impl/compact	line 24	Java Problem
Description	Resource	Path	Location	Type
Duplicate methods named fullIntAbstraction with the parameters (int, IntFunction<? extends I>) and (int, IntFunction<? extends I>) are defined by the type MutableDeterministic<Integer,I,Integer,O,Void>	CompactMoore.java	/automata-core/src/main/java/net/automatalib/automata/transducers/impl/compact	line 24	Java Problem
The compile enviroment is jdk1.8.
```
Has anyone encountered this problem?

**Comment by mtf90** [comment]
Dear @z11panyan, can you provide some more information on your build setup?

* What operating system are you using?
* What is the output of `java -version`?
* Are you using Maven to build AutomataLib?

That is an odd error that I cannot remember to have seen before...

**Comment by z11panyan** [comment]
The operating system is ubuntu16.04+eclipse4.15.0, java1.8.0_212, and the m2e is installed. I has used Maven cmd to build Automatalib. The command is 
```mvn clean compile
mvn install
mvn eclipse:eclipse
```
When I imported the automatalib into eclipse, the error occurred.

**Comment by mtf90** [comment]
Does the `mvn install` command execute without any errors? If so, then this doesn't look like an issue with AutomataLib itself.

I downloaded the latest version of Eclipse ([2021‑03 R](https://www.eclipse.org/downloads/packages/)) to reproduce the error myself and can confirm an issue on the `CompactMoore` class
```
Duplicate methods named setTransitions with the parameters (S, I, Collection<? extends T>) and (S, I, Collection<? extends T>) are defined by the type MutableDeterministic<Integer,I,Integer,O,Void>
```
Funnily enough, this is a different issue than you have encountered. Moreover, if you look at the `MutableDeterministic` class, there is only one definition of the above method. 

I believe Eclipse uses its own Java compiler (ecj) which may behave differently (i.e. may contain some bugs) compared to the official JDK compiler. Do you want to actively develop on AutomataLib or do you just want to use it in a seperate project? If the latter, you can just reference the Maven dependency (Eclipse also supports native Maven projects, so no need for `mvn eclipse:eclipse`) or download a pre-compiled `.jar` (see the `README.md` for further information on this).

Other than that, you can maybe try if the issue still persists with a different IDE (IntelliJ or NetBeans).

**Comment by z11panyan** [comment]
Thank you very much. Maybe Eclipse cannot support MAVEN very well, and I will try to use a different IDE

**Comment by z11panyan** [comment]
I tried the IntelliJ IDEA, the issue no longer exists. But when I did further experiments, I had an issue about the code. I had opened in the LearnLib,m and the link is https://github.com/LearnLib/learnlib/issues/76#issue-896542829. 
Looking forward to your reply.

**Comment by z11panyan** [comment]
I tried the IntelliJ IDEA, the issue no longer exists. But when I did further experiments, I had an issue about the code. I had opened in the LearnLib,m and the link is https://github.com/LearnLib/learnlib/issues/76#issue-896542829. 
Looking forward to your reply.

**Comment by mtf90** [comment]
So can *this* issue be closed then?

**Comment by z11panyan** [comment]
Yes, Thank you!
